"""
Unit tests for Bankinter VISA PDF to CSV Extractor.
"""

import os
from bankinter_visa_extractor.extractor import convert_pdf_to_csv


def test_convert_pdf_to_csv():
    """Test that the extractor correctly converts a sample PDF to a CSV."""
    print("Step 1: Setting up test paths...")
    pdf_path = "tests/sample_statement.pdf"  # Sample PDF for the test
    csv_path = "tests/output.csv"  # CSV file generated by the test

    print("Step 2: Running PDF to CSV conversion...")
    convert_pdf_to_csv(pdf_path, csv_path)

    print("Step 3: Verifying CSV file was created...")
    assert os.path.exists(csv_path), "CSV file was not created."

    print("Step 4: Cleaning up generated files...")
    os.remove(csv_path)

    print("✅ Test passed: PDF was successfully converted to CSV.")


if __name__ == "__main__":
    test_convert_pdf_to_csv()